import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Header from "@/components/Header/Header";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <Header />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
